[package]
name = "shibe-bot"
version = "0.2.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
log = "0.4.22"
poise = "0.6.1"
pretty_env_logger = "0.5.0"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
rand = "0.8.5"
serde = { version = "1.0.198", features = ["serde_derive"] }
serde_json = "1.0.128"
roux = "2.2.13"
rustc_version_runtime = "0.3.0"
build-time = "0.1.3"
